export const mockJobs = [
  {
    id: 1,
    title: "Backend Engineer",
    description: "Build APIs",
    contract_type: "FULL_TIME",
    office: "Paris",
    status: "published",
    work_mode: "remote",
    profession_id: 1,
    profession: null,
    applicants: [],
    inserted_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: 2,
    title: "Frontend Engineer",
    description: "Build Components",
    contract_type: "FULL_TIME",
    office: "London",
    status: "published",
    work_mode: "hybrid",
    profession_id: 1,
    profession: null,
    applicants: [],
    inserted_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
];
